package com.diozero.sdl.joystick;

public interface SdlEventTypes {
	int SDL_QUIT = 0x100;
	int SDL_JOYAXISMOTION = 0x600;
	int SDL_JOYBALLMOTION = 0x601;
	int SDL_JOYHATMOTION = 0x602;
	int SDL_JOYBUTTONDOWN = 0x603;
	int SDL_JOYBUTTONUP = 0x604;
	int SDL_JOYDEVICEADDED = 0x605;
	int SDL_JOYDEVICEREMOVED = 0x606;

	int SDL_CONTROLLERAXISMOTION = 0x650;
	int SDL_CONTROLLERBUTTONDOWN = 0x651;
	int SDL_CONTROLLERBUTTONUP = 0x652;
	int SDL_CONTROLLERDEVICEADDED = 0x653;
	int SDL_CONTROLLERDEVICEREMOVED = 0x654;
	int SDL_CONTROLLERDEVICEREMAPPED = 0x655;
	int SDL_CONTROLLERTOUCHPADDOWN = 0x656;
	int SDL_CONTROLLERTOUCHPADMOTION = 0x657;
	int SDL_CONTROLLERTOUCHPADUP = 0x658;
	int SDL_CONTROLLERSENSORUPDATE = 0x659;

	int SDL_JOYSTICK_EVENT_START = 0x600;
	int SDL_JOYSTICK_EVENT_END = 0x650;
	int SDL_GAMECONTROLLER_EVENT_START = 0x650;
	int SDL_GAMECONTROLLER_EVENT_END = 0x700;
}
